apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    user: ${DB_USER:-postgres}
    secureJsonData:
      password: ${DB_PASSWORD:-postgres}
    jsonData:
      database: ${DB_NAME:-maintenance_db}
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
    isDefault: true
